# Generated by Django 4.1.5 on 2023-01-12 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenity',
            name='description',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
